# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = '🍁 Payroll Administration'
copyright = '2025'
author = 'Alexandre Bobkov'
release = 'Fall 2025'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.mathjax",
    "sphinx.ext.imgmath",
    'sphinxcontrib.programoutput',
    'matplotlib.sphinxext.mathmpl',
    'sphinxcontrib.nwdiag',
    'sphinxcontrib.rackdiag',
    'sphinxcontrib.packetdiag',
    'sphinxcontrib.nwdiag',
    #"sphinx_favicon",
]

templates_path = ['_templates']
include_patterns = ['*.rst', '*.md']
exclude_patterns = []

# The master toctree document.
master_doc = 'index'
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
# The name of the default role to use for all documents.
default_role = 'literal'
# The encoding of source files.
source_encoding = 'utf-8-sig'
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
version = 'Fall 2025'


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

#html_theme = 'alabaster'
html_theme = 'classic'
html_static_path = ['_static']

latex_documents = [
    ('index', 'Payroll-Administration_2025.tex', 'Canadian Payroll Administration (2025)', 'Alexandre Bobkov', 'manual'),
]

# SimplePDF Customization

imgmath_image_format = 'png'
imgmath_dvi_png_args = ['-gamma', '1.5', '-D', '110', '-bg', 'Transparent']
imgmath_use_preview = True

simplepdf_style = 'default'
simplepdf_coverpage = True
simplepdf_toc_depth = 3
simplepdf_title = 'Canadian Payroll Administration (2025)'
simplepdf_author = 'Alexandre Bobkov'
simplepdf_css = '_static/simplepdf.css'
simplepdf_style = 'green'
simplepdf_file_name = 'Payroll Administration 2025.pdf'
simplepdf_vars = {
    #'primary': "#23A3EC",
    'links': '#FF3333',
    'bottom-center-content': '"Payroll Administration 2025"',
    'bottom-right-content': '"Alexandre Bobkov"',
}